import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import useAuthStore from '../hooks/useAuthStore'

const FEATURES = [
  { icon: '📜', title: 'Shayari Collection', desc: '200+ Hinglish & Hindi love shayari with custom styling', to: '/shayari' },
  { icon: '🎨', title: 'Romantic Templates', desc: 'Instagram posts, Story mode, Letter & Proposal pages', to: '/templates' },
  { icon: '💝', title: 'Love Quiz', desc: 'Create custom quizzes to test how well they know you', to: '/quiz' },
  { icon: '🤖', title: 'AI Love Messages', desc: 'Personalized romantic messages generated by Claude AI', to: '/ai' },
  { icon: '💌', title: 'Love Letter Mode', desc: 'Animated typewriter effect with music & petal rain', to: '/letter' },
  { icon: '📸', title: 'Photo Upload', desc: 'Upload couple photos with drag-and-drop, stored in cloud', to: '/templates' },
]

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.08 } }
}
const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  show:   { opacity: 1, y: 0, transition: { duration: 0.5 } }
}

export default function HomePage() {
  const { user } = useAuthStore()

  return (
    <main className="relative z-10 max-w-5xl mx-auto px-4 py-10">

      {/* Hero */}
      <motion.div className="text-center py-16"
        initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
        <h1 className="font-playfair text-5xl md:text-7xl leading-tight mb-5"
          style={{ background: 'linear-gradient(135deg,#f7c5d5 0%,#e8547a 45%,#d4a853 90%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
          Create Your<br /><em>Love Story</em>
        </h1>
        <p className="text-base md:text-lg max-w-lg mx-auto mb-10 leading-relaxed" style={{ color: '#9a6a7a' }}>
          Build personalized romantic pages, write shayari, generate AI love messages,
          and create fun quizzes for your special someone 💝
        </p>
        <div className="flex gap-3 justify-center flex-wrap">
          {user ? (
            <>
              <Link to="/templates" className="btn-rose">🌹 Start Creating</Link>
              <Link to="/ai" className="btn-gold">✨ AI Magic</Link>
              <Link to="/quiz" className="btn-ghost">💌 Make a Quiz</Link>
            </>
          ) : (
            <>
              <Link to="/register" className="btn-rose">🌹 Get Started Free</Link>
              <Link to="/login" className="btn-ghost">Sign In</Link>
            </>
          )}
        </div>
      </motion.div>

      {/* Features */}
      <motion.div
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-6"
        variants={stagger} initial="hidden" animate="show">
        {FEATURES.map(f => (
          <motion.div key={f.title} variants={fadeUp}>
            <Link to={user ? f.to : '/register'}
              className="block rounded-2xl p-5 transition-all duration-300 group"
              style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(232,84,122,0.12)' }}
              onMouseEnter={e => { e.currentTarget.style.background = 'rgba(232,84,122,0.08)'; e.currentTarget.style.borderColor = 'rgba(232,84,122,0.35)'; e.currentTarget.style.transform = 'translateY(-4px)'; }}
              onMouseLeave={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.04)'; e.currentTarget.style.borderColor = 'rgba(232,84,122,0.12)'; e.currentTarget.style.transform = 'translateY(0)'; }}>
              <div className="text-3xl mb-3">{f.icon}</div>
              <div className="font-medium text-rose-light mb-1.5">{f.title}</div>
              <div className="text-xs leading-relaxed" style={{ color: '#7a4a5a' }}>{f.desc}</div>
            </Link>
          </motion.div>
        ))}
      </motion.div>

      {/* Stats */}
      <motion.div
        className="grid grid-cols-3 gap-4 mt-16 text-center"
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}>
        {[['200+', 'Shayari'],['6', 'Templates'],['∞', 'Love']].map(([num, lbl]) => (
          <div key={lbl} className="glass-card py-6">
            <div className="font-playfair text-3xl mb-1" style={{ color: '#e8547a' }}>{num}</div>
            <div className="text-xs" style={{ color: '#7a4a5a' }}>{lbl}</div>
          </div>
        ))}
      </motion.div>
    </main>
  )
}
